### ISSUE TITLE
SSL Issue for nuget.org Connector

### ISSUE THREAD

**Issue by endeffects** [Inedo/proget-docker#12]
i'm receiving the following error when i try to retrieve packages over my nuget.org connector:

> Logged: 07/05/2019 19:09:53
>  Level: Error
>  Category: Connector
>  Message: Connector error: Error: TrustFailure (Authentication failed, see inner exception.)
>  Details: Request URL: https://www.nuget.org/api/v2/FindPackagesById()?id=%27System.Reflection.DispatchProxy%27&semVerLevel=2.0.0
> 
> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
> at /build/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
> at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00038] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000a1] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
> at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000ff] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0008b] in <e8eb3d7a311640f484845e45cbec8973>:0 
> --- End of inner exception stack trace ---
> at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00252] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x00126] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x001ba] in <e8eb3d7a311640f484845e45cbec8973>:0 
> --- End of inner exception stack trace ---
> at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x0021a] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00141] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Net.WebOperation.Run () [0x0009a] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <e8eb3d7a311640f484845e45cbec8973>:0 
> at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <6649516e5b3542319fb262b421af0adb>:0 
> --- End of stack trace from previous location where exception was thrown ---
> 
> at Inedo.ProGet.Feeds.StrongConnector.GetDirectResponseAsync (System.String url) [0x000eb] in <d9a7f6b53a9a4f9a9eccbddcc7403b15>:0 
> at Inedo.ProGet.Feeds.StrongConnector.GetCachedResponseAsync (System.String url) [0x000a8] in <d9a7f6b53a9a4f9a9eccbddcc7403b15>:0 
> at Inedo.ProGet.Feeds.StrongConnector.GetCachedTextReaderAsync (System.String url) [0x00075] in <d9a7f6b53a9a4f9a9eccbddcc7403b15>:0 
> at Inedo.ProGet.Feeds.NuGet.NuGetFeedClient.PerformRequestWithAbsoluteUrlAsync (System.String fullUrl) [0x000d9] in <d9a7f6b53a9a4f9a9eccbddcc7403b15>:0

**Comment by gdivis** [comment]
Hi-

Thanks for reaching out about this issue. Unfortunately it's not something I can easily diagnose on here, so I'm going to refer you to our official support page: (see [inedo.com/support](https://inedo.com/support)).

Using one of the resources there will allow more of our support staff and devs to see it and hopefully help get things resolved.

Thank you!
