### ISSUE TITLE
Please deploy: Proget 4.8.7 as docker image

### ISSUE THREAD

**Issue by cmenzi** [Inedo/proget-docker#2]
Because of the issue https://inedo.myjetbrains.com/youtrack/issue/PG-1126, we need to have the 4.8.7.

P.S:
- _Maybe you should setup CI/CD for this, as a CI/CD company_ :stuck_out_tongue_winking_eye:

**Comment by gdivis** [comment]
Sorry about that - just deployed v4.8.8 to docker.
