### ISSUE TITLE
[Question] - Any future plans for a windows image?

### ISSUE THREAD

**Issue by dazinator** [Inedo/proget-docker#3]
Just wondering if there was any future plans for a windows based image - or is that a bit premature?

**Comment by whatatripp** [comment]
It's a bit premature; Windows Containers aren't nearly production ready, and the advantages to using a container for something like ProGet (which is already very-well isolated) in a Windows environment is basically zero. Add to the fact that you require an external database and external package store, and you've given yourself even more headaches ;)

**Comment by dazinator** [comment]
Ok thanks for the follow up.

> and the advantages to using a container for something like ProGet (which is already very-well isolated) in a Windows environment is basically zero

Just to clarify - the benefit I had in mind when I asked about this is that it would enable ProGet to become part of an "infrastructure as code" definition. Being able to describe your infrastructure in a `docker-compose.yml` file as set of container images networked together is quite powerful. At the moment we can include tools like octopus deploy, team city, etc in that definition - but it would also be nice to include proget in that definition. In a recovery scenario, we can take that `yml` file to a docker host and run `docker-compose up` to see octopus, team city etc spin back up - but at the moment proget would remain a seperate set of recovery steps that someone would have to manage independently of that definition - unless of course we use the linux ProGet container image - however we are primarily a windows shop so introducing Linux is not really an option for us as we don't have those skills in house.

Still - perhaps when windows containers are more mature you might be willing to reconsider! :-)
